#pragma once

#include <Ludens/System/FileSystem.h>
#include <Ludens/Header/Math/Vec2.h>

namespace LD {

struct EditorUpdateTick
{
    float delta;     // delta time in seconds
    Vec2 screenSize; // window size
};

struct EditorProjectEntry
{
    FS::Path schemaPath;
    std::string projectName;
};

enum EditorUIMainLayout
{
    EDITOR_UI_MAIN_LAYOUT_SCENE = 0,
    EDITOR_UI_MAIN_LAYOUT_DOCS,
};

enum EditorWindowType
{
    EDITOR_WINDOW_TAB_CONTROL,
    EDITOR_WINDOW_ASSET_IMPORT,
    EDITOR_WINDOW_ASSET_SELECT,
    EDITOR_WINDOW_SCENE_SELECT,
    EDITOR_WINDOW_FILE_SELECT,
    EDITOR_WINDOW_CREATE_COMPONENT,
    EDITOR_WINDOW_PROJECT_SETTINGS,
    EDITOR_WINDOW_PROJECT,
    EDITOR_WINDOW_DOCUMENT,
    EDITOR_WINDOW_VIEWPORT,
    EDITOR_WINDOW_OUTLINER,
    EDITOR_WINDOW_INSPECTOR,
    EDITOR_WINDOW_CONSOLE,
    EDITOR_WINDOW_VERSION,
    EDITOR_WINDOW_TYPE_ENUM_COUNT,
};

enum EditorEventType
{
    EDITOR_EVENT_TYPE_NOTIFY_PROJECT_CREATION,
    EDITOR_EVENT_TYPE_NOTIFY_PROJECT_LOAD,
    EDITOR_EVENT_TYPE_NOTIFY_PROJECT_SETTINGS_DIRTY,
    EDITOR_EVENT_TYPE_NOTIFY_SCENE_LOAD,
    EDITOR_EVENT_TYPE_NOTIFY_COMPONENT_SELECTION,
    EDITOR_EVENT_TYPE_NOTIFY_FILE_DROP,
    EDITOR_EVENT_TYPE_REQUEST_SHOW_MODAL,
    EDITOR_EVENT_TYPE_REQUEST_HIDE_MODAL,
    EDITOR_EVENT_TYPE_REQUEST_WORKSPACE_LAYOUT,
    EDITOR_EVENT_TYPE_REQUEST_PROJECT_SETTINGS,
    EDITOR_EVENT_TYPE_REQUEST_COMPONENT_SCRIPT,
    EDITOR_EVENT_TYPE_REQUEST_COMPONENT_ASSET,
    EDITOR_EVENT_TYPE_REQUEST_IMPORT_ASSETS,
    EDITOR_EVENT_TYPE_REQUEST_OPEN_SCENE,
    EDITOR_EVENT_TYPE_REQUEST_OPEN_PROJECT,
    EDITOR_EVENT_TYPE_REQUEST_CREATE_SCENE,
    EDITOR_EVENT_TYPE_REQUEST_CREATE_PROJECT,
    EDITOR_EVENT_TYPE_REQUEST_CREATE_COMPONENT,
    EDITOR_EVENT_TYPE_REQUEST_DOCUMENT,
    EDITOR_EVENT_TYPE_ACTION_SAVE,
    EDITOR_EVENT_TYPE_ACTION_UNDO,
    EDITOR_EVENT_TYPE_ACTION_REDO,
    EDITOR_EVENT_TYPE_ACTION_OPEN_SCENE,
    EDITOR_EVENT_TYPE_ACTION_OPEN_PROJECT,
    EDITOR_EVENT_TYPE_ACTION_CREATE_SCENE,
    EDITOR_EVENT_TYPE_ACTION_CREATE_PROJECT,
    EDITOR_EVENT_TYPE_ACTION_IMPORT_ASSETS,
    EDITOR_EVENT_TYPE_ACTION_IMPORT_ASSETS_ASYNC,
    EDITOR_EVENT_TYPE_ACTION_RENAME_ASSET,
    EDITOR_EVENT_TYPE_ACTION_RENAME_SCENE,
    EDITOR_EVENT_TYPE_ACTION_RENAME_COMPONENT,
    EDITOR_EVENT_TYPE_ACTION_ADD_COMPONENT,
    EDITOR_EVENT_TYPE_ACTION_SET_COMPONENT_SCRIPT,
    EDITOR_EVENT_TYPE_ACTION_SET_COMPONENT_ASSET,
    EDITOR_EVENT_TYPE_ACTION_SET_COMPONENT_PROPS,
    EDITOR_EVENT_TYPE_ACTION_CLONE_COMPONENT_SUBTREE,
    EDITOR_EVENT_TYPE_ACTION_DELETE_COMPONENT_SUBTREE,
    EDITOR_EVENT_TYPE_ENUM_COUNT,
};

enum EditorEventCategory
{
    /// @brief Notify events signal a state change that observers may wish to adapt to.
    EDITOR_EVENT_CATEGORY_NOTIFY,

    /// @brief Request events signal that some process should be initiated,
    ///        no actions are committed yet and parameters are often unknown.
    EDITOR_EVENT_CATEGORY_REQUEST,

    /// @brief Action events are transactional and will affect Undo Redo state,
    ///        all parameters for the action type are already known.
    EDITOR_EVENT_CATEGORY_ACTION,
};

} // namespace LD
