#pragma once

#define PROJECT_SCHEMA_KEY_LUDENS_PROJECT "ludens_project"
#define PROJECT_SCHEMA_KEY_VERSION_MAJOR "version_major"
#define PROJECT_SCHEMA_KEY_VERSION_MINOR "version_minor"
#define PROJECT_SCHEMA_KEY_VERSION_PATCH "version_patch"
#define PROJECT_SCHEMA_KEY_NAME "name"
#define PROJECT_SCHEMA_KEY_ASSETS "assets"
#define PROJECT_SCHEMA_KEY_SCENES "scenes"

#define PROJECT_SCHEMA_TABLE_SETTINGS "settings"
#define PROJECT_SCHEMA_TABLE_STARTUP "startup"
#define PROJECT_SCHEMA_TABLE_SCREEN_LAYER "screen_layer"

#define PROJECT_SCHEMA_KEY_DEFAULT_SCENE_PATH "default_scene_path"
#define PROJECT_SCHEMA_KEY_STARTUP_WINDOW_NAME "window_name"
#define PROJECT_SCHEMA_KEY_STARTUP_WINDOW_WIDTH "window_width"
#define PROJECT_SCHEMA_KEY_STARTUP_WINDOW_HEIGHT "window_height"
