#pragma once

#define DEFAULT_STARTUP_WINDOW_WIDTH 1600
#define DEFAULT_STARTUP_WINDOW_HEIGHT 900
#define DEFAULT_STARTUP_WINDOW_NAME "Ludens"
#define DEFAULT_STARTUP_DEFAULT_SCENE_PATH {}

#define DEFAULT_RENDERING_CLEAR_COLOR Vec4(0.1f, 0.1f, 0.1f, 1.0f)