#pragma once

#define PROJECT_SCHEMA_KEY_LUDENS_PROJECT "ludensProject"
#define PROJECT_SCHEMA_KEY_VERSION_MAJOR "versionMajor"
#define PROJECT_SCHEMA_KEY_VERSION_MINOR "versionMinor"
#define PROJECT_SCHEMA_KEY_VERSION_PATCH "versionPatch"
#define PROJECT_SCHEMA_KEY_NAME "name"
#define PROJECT_SCHEMA_KEY_ASSETS "assets"
#define PROJECT_SCHEMA_KEY_SCENES "scenes"

#define PROJECT_SCHEMA_TABLE_SETTINGS "settings"
#define PROJECT_SCHEMA_TABLE_STARTUP "startup"
#define PROJECT_SCHEMA_TABLE_SCREEN_LAYER "screenLayer"

#define PROJECT_SCHEMA_KEY_DEFAULT_SCENE_PATH "defaultScenePath"
#define PROJECT_SCHEMA_KEY_STARTUP_WINDOW_NAME "windowName"
#define PROJECT_SCHEMA_KEY_STARTUP_WINDOW_WIDTH "windowWidth"
#define PROJECT_SCHEMA_KEY_STARTUP_WINDOW_HEIGHT "windowHeight"
