#pragma once

#define EDITOR_BAR_HEIGHT 22.0f
#define EDITOR_TOP_BAR_WORKSPACE_NAME "TOP_BAR_WORKSPACE"
#define EDITOR_TOP_BAR_WINDOW_NAME "TOP_BAR_WINDOW"
#define EDITOR_TOP_BAR_MENU_FILE_NAME "TOP_BAR_MENU_FILE"
#define EDITOR_TOP_BAR_MENU_EDIT_NAME "TOP_BAR_MENU_EDIT"
#define EDITOR_TOP_BAR_MENU_ABOUT_NAME "TOP_BAR_MENU_ABOUT"

#define EDITOR_UI_CONTEXT_NAME "EDITOR_UI"
#define EDITOR_UI_LAYER_TOP_BAR_NAME "EDITOR_UI_LAYER_TOP_BAR"
#define EDITOR_UI_LAYER_MAIN_NAME "EDITOR_UI_LAYER_MAIN"
#define EDITOR_UI_LAYER_MODAL_NAME "EDITOR_UI_LAYER_MODAL"
#define EDITOR_UI_DIALOG_CONTEXT_NAME "EDITOR_UI_DIALOG"
#define EDITOR_UI_DIALOG_LAYER_NAME "EDITOR_UI_DIALOG"
