#pragma once

#define SCENE_SCHEMA_TABLE_LUDENS_SCENE "ludens_scene"
#define SCENE_SCHEMA_KEY_VERSION_MAJOR "version_major"
#define SCENE_SCHEMA_KEY_VERSION_MINOR "version_minor"
#define SCENE_SCHEMA_KEY_VERSION_PATCH "version_patch"

#define SCENE_SCHEMA_TABLE_HIERARCHY "hierarchy"
#define SCENE_SCHEMA_TABLE_COMPONENT "component"

#define SCENE_SCHEMA_KEY_COMPONENT_ID "id"
#define SCENE_SCHEMA_KEY_COMPONENT_TYPE "type"
#define SCENE_SCHEMA_KEY_COMPONENT_NAME "name"
#define SCENE_SCHEMA_KEY_COMPONENT_TRANSFORM "transform"
#define SCENE_SCHEMA_KEY_COMPONENT_SCRIPT_ID "script_id"

#define SCENE_SCHEMA_KEY_MESH_MESH_ID "mesh_id"

#define SCENE_SCHEMA_KEY_AUDIO_SOURCE_CLIP_ID "clip_id"
#define SCENE_SCHEMA_KEY_AUDIO_SOURCE_PAN "pan"
#define SCENE_SCHEMA_KEY_AUDIO_SOURCE_VOLUME_LINEAR "volume_linear"

#define SCENE_SCHEMA_KEY_SPRITE_2D_PIVOT "pivot"
#define SCENE_SCHEMA_KEY_SPRITE_2D_REGION "region"
#define SCENE_SCHEMA_KEY_SPRITE_2D_Z_DEPTH "z_depth"
#define SCENE_SCHEMA_KEY_SPRITE_2D_TEXTURE_2D_ID "texture_2d_id"
#define SCENE_SCHEMA_KEY_SPRITE_2D_SCREEN_LAYER_ID "screen_layer_id"

#define SCENE_SCHEMA_KEY_CAMERA_IS_MAIN "is_main"
#define SCENE_SCHEMA_KEY_CAMERA_IS_PERSPECTIVE "is_perspective"
#define SCENE_SCHEMA_TABLE_CAMERA_PERSPECTIVE "perspective"
#define SCENE_SCHEMA_KEY_CAMERA_PERSPECTIVE_FOV "fov"
#define SCENE_SCHEMA_KEY_CAMERA_PERSPECTIVE_FAR_CLIP "far_clip"
#define SCENE_SCHEMA_KEY_CAMERA_PERSPECTIVE_NEAR_CLIP "near_clip"
#define SCENE_SCHEMA_TABLE_CAMERA_ORTHOGRAPHIC "orthographic"
#define SCENE_SCHEMA_KEY_CAMERA_ORTHOGRAPHIC_LEFT "left"
#define SCENE_SCHEMA_KEY_CAMERA_ORTHOGRAPHIC_RIGHT "right"
#define SCENE_SCHEMA_KEY_CAMERA_ORTHOGRAPHIC_TOP "top"
#define SCENE_SCHEMA_KEY_CAMERA_ORTHOGRAPHIC_BOTTOM "bottom"
#define SCENE_SCHEMA_KEY_CAMERA_ORTHOGRAPHIC_NEAR_CLIP "near_clip"
#define SCENE_SCHEMA_KEY_CAMERA_ORTHOGRAPHIC_FAR_CLIP "far_clip"

#define SCENE_SCHEMA_KEY_SCREEN_UI_UI_TEMPLATE_ID "ui_template_id"
