#pragma once

namespace LD {

enum ComponentType
{
    COMPONENT_TYPE_DATA = 0,
    COMPONENT_TYPE_AUDIO_SOURCE,
    COMPONENT_TYPE_TRANSFORM,
    COMPONENT_TYPE_TRANSFORM_2D,
    COMPONENT_TYPE_CAMERA,
    COMPONENT_TYPE_CAMERA_2D,
    COMPONENT_TYPE_MESH,
    COMPONENT_TYPE_SPRITE_2D,
    COMPONENT_TYPE_SCREEN_UI,
    COMPONENT_TYPE_ENUM_COUNT,
};

enum Camera2DConstraint
{
    CAMERA_2D_CONSTRAINT_FREE,
    CAMERA_2D_CONSTRAINT_FIXED,
};

} // namespace LD