if(MSVC)
    set(MODULE_COMPILE_OPTIONS /W4 /wd4201)
    set(MODULE_LINK_OPTIONS "/ignore:4099")
else()
    set(MODULE_COMPILE_OPTIONS -Wall -Wextra)
endif()

function(add_ludens_core_module)
    cmake_parse_arguments(MODULE "" "NAME" "INCLUDE;LIB" ${ARGN})
    message(STATUS "LUDENS CORE MODULE          ${MODULE_NAME}")
    set(LD_CORE_MODULE_LIST "${LD_CORE_MODULE_LIST};${MODULE_NAME}" CACHE STRING "" FORCE)
    add_library(${MODULE_NAME} STATIC ${MODULE_INCLUDE} ${MODULE_LIB})
    target_include_directories(${MODULE_NAME} PRIVATE ${LUDENS_INCLUDE_DIR})
    target_compile_options(${MODULE_NAME} PRIVATE ${MODULE_COMPILE_OPTIONS})
    target_link_options(${MODULE_NAME} PRIVATE ${MODULE_LINK_OPTIONS})
    set_target_properties(${MODULE_NAME} PROPERTIES FOLDER ${LD_CORE_MODULE_FOLDER})
endfunction()

function(add_ludens_core_module_test)
    cmake_parse_arguments(MODULE "" "TEST_NAME" "TEST" ${ARGN})
    message(STATUS "LUDENS CORE MODULE TEST     ${MODULE_TEST_NAME}")
    add_executable(${MODULE_TEST_NAME} ${MODULE_TEST})
    target_include_directories(${MODULE_TEST_NAME} PRIVATE ${LUDENS_INCLUDE_DIR} ${LUDENS_SOURCE_DIR})
    target_link_options(${MODULE_TEST_NAME} PRIVATE ${MODULE_LINK_OPTIONS})
    set_target_properties(${MODULE_TEST_NAME} PROPERTIES FOLDER ${LD_CORE_MODULE_FOLDER})
endfunction()

function(add_ludens_builder_module)
    cmake_parse_arguments(MODULE "" "NAME" "INCLUDE;LIB" ${ARGN})
    message(STATUS "LUDENS BUILDER MODULE       ${MODULE_NAME}")
    set(LD_BUILDER_MODULE_LIST "${LD_BUILDER_MODULE_LIST};${MODULE_NAME}" CACHE STRING "" FORCE)
    add_library(${MODULE_NAME} STATIC ${MODULE_INCLUDE} ${MODULE_LIB})
    target_include_directories(${MODULE_NAME} PRIVATE ${LUDENS_INCLUDE_DIR} ${LUDENS_SOURCE_DIR})
    target_compile_options(${MODULE_NAME} PRIVATE ${MODULE_COMPILE_OPTIONS})
    target_link_libraries(${MODULE_NAME} PUBLIC LDCoreLibs)
    target_link_options(${MODULE_NAME} PRIVATE ${MODULE_LINK_OPTIONS})
    set_target_properties(${MODULE_NAME} PROPERTIES FOLDER ${LD_BUILDER_MODULE_FOLDER})
endfunction()

function(add_ludens_editor_module)
    cmake_parse_arguments(MODULE "" "NAME" "INCLUDE;LIB" ${ARGN})
    message(STATUS "LUDENS EDITOR MODULE        ${MODULE_NAME}")
    set(LD_EDITOR_MODULE_LIST "${LD_EDITOR_MODULE_LIST};${MODULE_NAME}" CACHE STRING "" FORCE)
    add_library(${MODULE_NAME} STATIC ${MODULE_INCLUDE} ${MODULE_LIB})
    target_include_directories(${MODULE_NAME} PRIVATE ${LUDENS_INCLUDE_DIR} ${LUDENS_SOURCE_DIR})
    target_compile_options(${MODULE_NAME} PRIVATE ${MODULE_COMPILE_OPTIONS})
    target_link_libraries(${MODULE_NAME} PUBLIC LDCoreLibs LDBuilderLibs)
    target_link_options(${MODULE_NAME} PRIVATE ${MODULE_LINK_OPTIONS})
    set_target_properties(${MODULE_NAME} PROPERTIES FOLDER ${LD_EDITOR_MODULE_FOLDER})
endfunction()

function(add_ludens_editor_module_test)
    cmake_parse_arguments(MODULE "" "TEST_NAME" "TEST" ${ARGN})
    message(STATUS "LUDENS EDITOR MODULE TEST   ${MODULE_TEST_NAME}")
    add_executable(${MODULE_TEST_NAME} ${MODULE_TEST})
    target_include_directories(${MODULE_TEST_NAME} PRIVATE ${LUDENS_INCLUDE_DIR} ${LUDENS_SOURCE_DIR})
    target_link_libraries(${MODULE_TEST_NAME} PUBLIC LDCoreLibs LDBuilderLibs)
    target_link_options(${MODULE_TEST_NAME} PRIVATE ${MODULE_LINK_OPTIONS})
    set_target_properties(${MODULE_TEST_NAME} PROPERTIES FOLDER ${LD_EDITOR_MODULE_FOLDER})
endfunction()